### ISSUE TITLE
Plex installer not install PMS

### ISSUE THREAD

**Issue by kaosb** [blindpet/MediaServerInstaller#1]
Do not install Plex media server

**Comment by blindpet** [comment]
This is for compatibility on x86 and x64 systems, you should find on ARM both packages point to the installer.

**Comment by kaosb** [comment]
Yeah arm7 raspberry 2 and raspbian jessie

you know any solution for now?

Thanks.

## 

_Felipe I. González G._
Software Engineer
+56997984417 <//+56-9-97984417>

El 16 de julio de 2016 a las 04:01:47, blindpet (notifications@github.com)
escribió:

This is for compatibility on x86 and x64 systems, you should find on ARM
both packages point to the installer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/blindpet/MediaServerInstaller/issues/1#issuecomment-233118766,
or mute the thread
