### ISSUE TITLE
Kodi install on Pi 3 fails with message: not Raspberry Pi...

### ISSUE THREAD

**Issue by mattia72** [blindpet/MediaServerInstaller#2]
Hi,

I followed the instructions from here:
http://www.htpcguides.com/lightweight-raspbian-distro-minibian-initial-setup/
and then from here:
http://www.htpcguides.com/raspberry-pi-2-home-media-server-installer-image/

As I wanted to install Kodi, the installer exited with this message: 
`not Raspberry Pi...`

Transmission and miniDLNA installation went without any error.

**Comment by wpbullet** [comment]
Can you provide the output of 

`uname -a`

**Comment by HTPCGuides** [comment]
Can you provide the output of 

`uname -a`

**Comment by mattia72** [comment]
Of course:
Linux minibian 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux

**Comment by HTPCGuides** [comment]
Thank you, please do a git pull to update and try again

**Comment by mattia72** [comment]
It rocks :) Thank you for the quick support!
